### ISSUE TITLE
[Crash] CBCClassesRespondingToSelector crashes on 10.3 when using Reveal

### ISSUE THREAD

**Issue by willlarche** [material-foundation/cocoapods-catalog-by-convention#10]
# Overview

On [MDCCatalog](github.com/material-components/material-components-ios), with 10.3 simulator (Xocde 8.3 Beta 1-5), running [Reveal](https://revealapp.com/) via [breakpoint injection](http://support.revealapp.com/kb/getting-started/load-the-reveal-server-via-an-xcode-breakpoint),  it will crash when asking WebKit classes if they respond to selector (during the navigation tree creation.)

```objc
if ([aClass respondsToSelector:selector])
```

# Workaround:

Ignore classes starting with "WK". Not a true solution but will work until a solution.

```objc
NSArray<Class> *CBCClassesRespondingToSelector(NSArray<Class> *classes, SEL selector) {
  NSMutableArray<Class> *filteredClasses = [NSMutableArray array];

  for (Class aClass in classes) {
    NSString *catch = NSStringFromClass(aClass);
    if ([catch containsString:@"WK"]) {
      continue;
    }

    if ([aClass respondsToSelector:selector]) {
      [filteredClasses addObject:aClass];
    }
  }
  return filteredClasses;
}
```

**Comment by chuckhays** [comment]
I hit this issue and "fixed" it by adding WK to the ignored prefix list:
NSArray *ignoredPrefixes = @[ @"Swift.", @"_", @"JS", @"WK" ];

Same fix, different place.

**Comment by romoore** [comment]
No longer crashes. Looks like the filtering was added.
