### ISSUE TITLE
Profile the Catalog By Convention on-device runtime cost of initializing the navigation tree and explore improvements

### ISSUE THREAD

**Issue by jverkoey** [material-foundation/cocoapods-catalog-by-convention#21]
There have been reports that app startup time is noticeably degraded in complex apps that make use of the catalog by convention. It's decently likely that our enumeration of the runtime is playing a part in this.

- [ ] Profile the [Material Components for iOS](https://github.com/material-components/material-components-ios) catalog app on a device.
- [ ] If costly code is discovered, send a PR to address the cost (likely be some mechanism of caching or alternative runtime APIs).

**Comment by romoore** [comment]
I've previously taken a look at this possibility as part of an internal issue. On an iPhone 5c/iOS 10.3.3 I did not find that CbC significantly impacted app performance.

**Comment by romoore** [comment]
### Overall MDC Catalog Launch Profile

**Test device: iPhone 5c/iOS 10.3.3**

Initial startup (just after install) is the most costly. The system requires approximately 4 seconds to initialize the application. Application launch then consumes an additional 2 seconds.  Of these 2 seconds, approximately 750 ms is dedicated to Catalog By Convention activity.  Subsequent launches (cached) take around 670 ms for Catalog By Convention to execute.

Launch Sequence No. | Initializing (ms) | Launching (ms) | CbC (ms) | Next-top | Foreground After
-----------------------|----------------|----------------|-----------|----------|-----
0 (Install)                       |4,100 |2,150|744|`window.makeKeyAndVisible()` (16 ms) | 6,250
1                                     |1,350 | 1,950 | 685 | `window.makeKeyAndVisible()` (12 ms) | 3,300
2                                     |1,310 | 1,900 | 672 | `window.makeKeyAndVisible()` (12 ms) | 3,200

### Analysis of Catalog By Convention CPU utilization
Most of the time spent in CbC is to iterate the list of classes in the application and adding potential examples to an `NSMutableArray`.  Of the ~675 ms spent on CbC, around 428 ms is spent adding potential examples to the array.  Once the list of potential classes is generated, it is filtered to include only those classes that respond to the selector `catalogBreadcrumbs`. This filtering takes approximately 65 ms.

#### Baseline Catalog By Convention Performance
Selector | Time Spent
---------|------------
CBCGetAllClasses | 553 ms
CBCClassesRespondingToSelector | 65 ms
CBCCreateTreeWithOnlyPresentable | 29 ms
CBCCatalogInvokeFromClassAndSelector | 10 ms

**Screenshot of Time Profiler (Instruments) for Baseline Catalog By Convention**
![cbc_overall_stable](https://user-images.githubusercontent.com/1753199/34161853-df4bb692-e49f-11e7-9fb6-ebc4a4c19200.png)

Although [adding objects to an `NSMutableArray` is an individually fast operation](http://www.learn-cocos2d.com/2010/09/array-performance-comparison-carray-ccarray-nsarray-nsmutablearray/), it's clear that adding so many classes is taking the most amount of time.  We are adding all of the system library classes, MDC-iOS classes, and anything else brought into the application.  These classes will later be filtered based on their response to the selector `catalogBreadcrumbs`.  Trying to preallocate the size of the `NSMutableArray` has no significant impact on performance, and so it not helpful trying to improve performance.

**Screenshot of Time Profiler (Instruments) for Baseline `CBCGetAllClasses`**
![cbcgetallclasses_stable](https://user-images.githubusercontent.com/1753199/34162536-12aa6392-e4a2-11e7-8685-ed79e7e6e887.png)


#### UIViewController-based Filtering for Improving Catalog By Convention Performance
Building an array containing so many classes and then filtering each of them by [checking their response to a selector is slow](https://stackoverflow.com/questions/12117670/performance-penalty-using-respondstoselector).  Instead, we can note that [every example in CatalogByConvention is required to be a UIViewController or subclass](https://github.com/material-foundation/cocoapods-catalog-by-convention/blob/develop/src/CBCNodeListViewController.m#L171). Using this knowledge, we can save a little time by selecting only those classes that inherit from `UIViewController`. This is a much faster comparison (by checking the `isa` value up the inheritance chain). On a `Class` object, `isSubclassOfClass:` is the correct method to invoke.

Once we add this filtering to `CBCGetAllClasses`, we directly save around 20 ms. Elsewhere in the initialization graph, we save another 80 ms.

Selector | Time Spent | Change (%)
---------|------------|--------
CBCGetAllClasses | 532 ms | -20 ms (-4%)
CBCCreateTreeWithOnlyPresentable | 12 ms | -17 ms (-41%)
CBCCatalogInvokeFromClassAndSelector | 9 ms | -1 ms (-10%)
... | ...
CBCClassesRespondingToSelector | 2 ms | -63 ms (-97%)

![cbc_overall_uivc-filter](https://user-images.githubusercontent.com/1753199/34162516-0257fa86-e4a2-11e7-8db4-b77408dc876f.png)

**Comment by romoore** [comment]
The same change saved around 30ms (11%) on an iPad Mini 4/iOS 10.3.2:

**Screenshot of Time Profiler (Instruments) for Baseline Catalog By Convention**
![cbc_overall_stable-ipad](https://user-images.githubusercontent.com/1753199/34164404-71714080-e4a7-11e7-8d64-8f47624adf2a.png)

**Screenshot of Time Profiler (Instruments) for UIViewController-based filtering Catalog By Convention**
![cbc_overall_uivc-filter-ipad](https://user-images.githubusercontent.com/1753199/34164430-833c7d16-e4a7-11e7-9d1a-205ade2faf83.png)
