### ISSUE TITLE
Formalize a generalized pattern for returning example metadata

### ISSUE THREAD

**Issue by jverkoey** [material-foundation/cocoapods-catalog-by-convention#25]
Currently, to add new metadata to examples we need to add new APIs to the library and cut a release, e.g. #24.

If we had a more generalized mechanism for defining example metadata then we would be able to move all metadata definitions into the downstream apps. This would mean fewer releases of catalog by convention.

For example, one possible solution is to define an `+ catalogMetadata` API that returns a dictionary. The app could then define keys it expects examples to implement.

**Comment by jverkoey** [comment]
@yarneo was hacking on similar code recently - want to take a stab?

**Comment by yarneo** [comment]
Sure thing!

**Comment by yarneo** [comment]
This has been resolved in PR #27
