### ISSUE TITLE
App crashes in iOS 12 beta sim (Xcode 10b4)

### ISSUE THREAD

**Issue by heinberg** [material-foundation/cocoapods-catalog-by-convention#30]
https://github.com/material-foundation/cocoapods-catalog-by-convention/blob/c4ab199e59c84ca93c88b4e0bf4d50c0558afc36/src/private/CBCRuntime.m#L151

Our app crashes upon start in the sim (the same occurs on an actual device running iOS 12 beta). The stacktrace shows that it fails within isSubclassOfClass with EXC_BAD_INSTRUCTION.

**Comment by jverkoey** [comment]
What is your Xcode version? We're not able to repro a crash on the MDC catalog with Xcode 10L213o.

**Comment by jverkoey** [comment]
Also can you provide a stack trace plus a print out of the `aClass` value?
